[package]
name = "aoc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
intersection = "1.0.0"
itertools = "0.12.1"
# colored = "2.1.0"
test-case = "3.3.1"
nohash-hasher = "0.2.0"