[package]
name = "aoc2022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
intersection = "1.0.0"
itertools = "0.12.1"
test-case = "3.3.1"
anyhow = "1.0.80"
num = "0.4.1"
pathfinding = "4.9.1"
