[package]
name = "aoc2022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
intersection = "1.0.0"
itertools = "0.12.1"
test-case = "3.3.1"
anyhow = "1.0.81"
num = "0.4.1"
pathfinding = "4.9.1"
regex = "1.10.4"
array2d = "0.3.2"
derive_deref = "1.1.1"
rayon = "1.10.0"
petgraph = "0.6.4"
